# Generated by Django 4.2.7 on 2023-11-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('phone', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=70, unique=True)),
                ('dob', models.DateField()),
                ('age', models.CharField(max_length=2)),
                ('address', models.CharField(max_length=500)),
                ('place', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
            ],
        ),
    ]
