# Generated by Django 4.2.7 on 2023-11-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='fee',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
