# Generated by Django 4.2.7 on 2023-11-15 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_admission_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='fee',
        ),
    ]
