# Generated by Django 4.2.7 on 2023-11-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_placements'),
    ]

    operations = [
        migrations.AddField(
            model_name='placements',
            name='name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
