# Generated by Django 4.1.6 on 2023-11-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_placements_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placements',
            options={'ordering': ['-id']},
        ),
    ]
