# Generated by Django 4.2.7 on 2023-11-25 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_placements_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='age',
        ),
    ]
